id: A6EBB96C6
title: Upon Arriving at Yangleshö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:06:41.789016
  last_modified_at: 2022-03-01 05:06:41.789019
