id: A6EBB96C6
title: Prayer of Aspiration to the Stūpa Commemorating the Bodily Sacrifice to the
  Tigress
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:06:41.785986
  last_modified_at: 2022-03-01 05:06:41.785988
