id: A6EBB96C6
title: A Prayer to the Three Stūpas of Nepal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:06:41.777750
  last_modified_at: 2022-03-01 05:06:41.777756
