id: A6EBB96C6
title: A Prayer to the Svayambhū Stūpa in Nepal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:06:41.775547
  last_modified_at: 2022-03-01 05:06:41.775551
