id: A6EBB96C6
title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress of the
  Jarung Kashor Stūpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:06:41.769859
  last_modified_at: 2022-03-01 05:06:41.769867
