id: A6EBB96C6
title: In Praise of Yangleshö in Nepal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:06:41.784374
  last_modified_at: 2022-03-01 05:06:41.784378
