id: A6EBB96C6
title: Prayer to the Three Great Stūpas of Kathmandu
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:06:41.787448
  last_modified_at: 2022-03-01 05:06:41.787451
