id: A6EBB96C6
title: 'Gathering Auspiciousness: A Prayer of Aspiration Made in the Presence of the
  Sacred Mahābodhi Temple and its Imagery, Magadha, Land of the Āryas'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:06:41.782621
  last_modified_at: 2022-03-01 05:06:41.782624
